version: '3'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0 -p 5000
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  web2:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0 -p 5001
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5001:5001
    env_file:
      - ./.env2.dev
    depends_on:
      - db
  
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on: 
      - web

volumes:
  postgres_data: